import "@/styles/globals.css";

import { type Metadata } from "next";
import { Courier_Prime, Cutive, Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/hooks/use-theme";
 import { SessionProvider } from "next-auth/react";
import type { Session } from "next-auth";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});
const courier = Courier_Prime({
  subsets: ["latin"],
  variable: "--font-courier",
  weight: ["400", "700"]
});

export default function RootLayout({
  children,
  session,
}: Readonly<{ children: React.ReactNode, session: Session }>) {
  return (
    <html lang="en" className={cn(geist.variable, courier.variable)}>
      <body>
        <SessionProvider session={session}>
          <ThemeProvider>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
